version: "3"

services:
    app:
        build: .
        environment:
            PORT: 3000
            PGHOST: ${PGHOST}
            PGUSER: ${PGUSER}
            PGDATABASE: ${PGDATABASE}
            PGPASSWORD: ${PGPASSWORD}
            PGPORT: ${PGPORT}
        ports:
            - 3000:3000
        depends_on:
            - db

    db:
        image: postgres:13.3
        container_name: ${PGHOST}
        environment:
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_DB: ${PGDATABASE}
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - ${PGPORT}:5432

volumes:
    db-data:
