version: "3"

services:
    app:
        build: .
        environment:
            PORT: 3000
        ports:
            - 3000:3000
        depends_on:
            - db

    db:
        image: postgres:13.3
        container_name: postgres_url_shortener
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_password
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "pgadmin@example.com"
            PGADMIN_DEFAULT_PASSWORD: "pgadmin"
        ports:
            - 5050:80
        depends_on:
            - db

volumes:
    db-data:
