version: "3"

services:
    server:
        build: ./server
        environment:
            PORT: ${PORT}
            PGHOST: ${PGHOST}
            PGUSER: ${PGUSER}
            PGDATABASE: ${PGDATABASE}
            PGPASSWORD: ${PGPASSWORD}
            PGPORT: ${PGPORT}
        ports:
            - "3000:3000"
        depends_on:
            - db

    db:
        image: postgres:13.3
        container_name: ${PGHOST}
        environment:
            POSTGRES_USER: ${PGUSER}
            POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_DB: ${PGDATABASE}
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - ${PGPORT}:5432

    nginx:
        build: ./nginx
        volumes:
            - ./client/dist:/usr/share/nginx/html
        ports:
            - "8081:3000"
            - "8080:80"
        depends_on:
            - server

volumes:
    db-data:
